<?php $this->render('common/header'); ?>
    <div class="page-header">
        <h1>Agenda - TreinaWeb Cursos</h1>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">

            <a href="<?=url()->route('cadastro.index')?>" class="btn btn-success">
                Cadastrar Pessoa
            </a>

        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">

            Selecione a pessoa:
            <select id="pessoas">
                <option value="0"> Selecione</option>
                <option value="0">Colocar as Pessoas aqui</option>
            </select>

        </div>
    </div>
    
    <script type="text/javascript">
        $(document).ready(function(){
            $('#pessoas').change(function(){
                //document.location.href = '<?=url()->route('eventos.index', ['pessoa' => '']);?>' + $(this).val();
            });
        });
    </script>

<?php $this->render('common/footer'); ?>