<?php $this->render('common/header'); ?>

    <div class="page-header">
        <h1>Eventos de <strong><?='Nome da pessoa'?></strong></h1>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">

            <a href="<?=url()->route('eventos.cadastrar')?>" class="btn btn-success">
                Novo Evento
            </a>

        </div>
    </div>

    <?php if(session()->has('_sucesso')): ?>
    <div class="alert alert-success" role="alert"><?=session()->getAndRemove('_sucesso');?></div>
    <?php endif;  ?>

    <?php if(session()->has('_erro')): ?>
        <div class="alert alert-warning" role="alert"><?=session()->getAndRemove('_erro');?></div>
    <?php endif;  ?>

    <div class="agenda">
        <div class="table-responsive">
            <table class="table table-condensed table-bordered">
                <thead>
                <tr>
                    <th>Data</th>
                    <th>Hora</th>
                    <th>Evento</th>
                    <th>Editar</th>
                </tr>
                </thead>
                <tbody>

                    <?php
                    $mockEventos[0] = (object)[
                        'id' => 1,
                        'data' => '2015-09-20',
                        'hora_de' => '11:00',
                        'hora_ate' => '15:00',
                        'descricao' => 'Descrição teste para o Mock'
                    ];
                    foreach($mockEventos as $evento): 
                    ?>

                    <tr>
                        <td class="agenda-date" class="active" rowspan="1">
                            <div class="dayofmonth"><?=dt($evento->data)->getDayOfMonth();?></div>
                            <div class="dayofweek"><?=dt($evento->data)->getDayOfWeek();?></div>
                            <div class="shortdate text-muted"><?=dt($evento->data)->getYearAndMonthSpelledOut();?></div>
                        </td>
                        <td class="agenda-time">
                            <?=$evento->hora_de;?>

                            <?php if($evento->hora_ate): ?>
                                às <?=$evento->hora_ate;?>
                            <?php endif; ?>
                        </td>
                        <td class="agenda-events">
                            <?=$evento->descricao;?>
                        </td>
                        <td class="agenda-events">
                            <a href="<?=url()->route('eventos.cadastrar', ['evento' => $evento->id]);?>">
                                Editar
                            </a>
                        </td>
                    </tr>

                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>

        <a class="btn btn-info" href="<?=url()->route('index');?>">Voltar</a>

    </div>

<?php $this->render('common/footer'); ?>

